[default]
heuristic-name = evidence_driven
data-name = edsm_data

mode=greedy


; ====== search order parameters ======
; color any blue node red that cannot be merged with any red node
extend = 1

; only consider the blue node closest to the root
; (alphabetical for tie breakers)
shallowfirst = 1

; only consider the blue node that occurs the most frequent
largestblue = 1

; also allow merges between pairs of blue nodes,
; the resulting node is colored red 
blueblue = 1

; disallow merges that add new edges to red nodes 
redfixed = 1

; disallow merges with a score below lowerboundval
lowerbound = 0
lowerboundval = 0


; ===== sink settings =====

; use sinks? if set to true blue nodes that occur less frequent
; than sinkcount are not considered for merging
; after one merge run, sink states remain in the automaton
sinkson = 0
sinkcount = 0
; do something with sinks?
; start a second merge run only for sink states
mergesinks = 0
; start a search process to merge the sinks with the red core
searchsinks = 0
; print the remaining nodes after merging (e.g. sinks)
printblue = 0
printwhite = 0

; nodes and transitions less frequent than these counts
; are not used in evaluation function heuristics
state_count = 0
symbol_count = 0

; ====== search settings =====
; for search set mode=search
; a best-first search process, using greedy runs as estimates
searchdeep = 0
; a best-first search process, using the greedy eval function
searchlocal = 0
; a timeout for search in seconds
; the best model is returned
searchtimeout = 10

; ====== use alergia to learn a classifier =====
; heuristic-name = alergia
; data-name = alergia-data
; typedist = 1
; finalprob = 1

